### ISSUE TITLE
RouterOS 6.46 is broken

### ISSUE THREAD

**Issue by nathanfaber** [svlsResearch/ha-mikrotik#16]
Do not upgrade to 6.46, auto scripts do not work and ha-mikrotik will not work correctly. If you use the latest version of ha-mikrotik from git master, you will get an error "ha_checkchanges: unable to find xxx/yyy! is auto working on this platform? xxxOffset: yyyOffset".

**Comment by fflo** [comment]
Any news or update on this issue?

**Comment by nathanfaber** [comment]
I haven't had a chance to test the newer RouterOS releases but I can try to take a look and see if they have fixed it.

**Comment by nathanfaber** [comment]
It looks like it may be fixed. I just upgraded a pair to `6.45.8 (long-term)` and did some quick checks using the current master `0.7test15 - de3cd22b6c4882782ab0c7bf2903cdce9668264c` and it looks OK.

If you are able to test this, please do. I will update once I feel like it is sufficiently burned in.

**Comment by fflo** [comment]
Confirm. 6.45.8 seems to work stable with ha-mikrotik.

**Comment by ericngv** [comment]
I am using 6.46.6 testing in my office and it seems to be stable.

**Comment by nathanfaber** [comment]
> I am using 6.46.6 testing in my office and it seems to be stable.

Thanks for confirming. I have switched one of my pairs to 6.46.6 to test as well. Looks good so far.

**Comment by nathanfaber** [comment]
6.46.6 has been stable.
