### ISSUE TITLE
Web interface doesn't respond after failover

### ISSUE THREAD

**Issue by miken32** [svlsResearch/ha-mikrotik#19]
Have been testing this script with a couple of RB2011s and things are working well for the most part. One thing I can't figure out is the secure web interface does not operate after failure to the B router. Firefox complains about `NO_CIPHER_OVERLAP` and sure enough, a check with `openssl` gives me this output:

```
$ openssl s_client -host 192.168.243.1 -port 443
CONNECTED(00000003)
4332498368:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1544:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 293 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

The certificate, key, and CA are all present on the router, and there are no errors in the log. Restarting the www-ssl service does not help. Returning service to the A box restores access. Is this a known problem?

**Comment by nathanfaber** [comment]
Hmm we don't use www-ssl internally so I'm not positive if this works or not, does www service continue to work? I can test the ssl service in a bit and get back. What RouterOS version?

**Comment by miken32** [comment]
6.44.6. Yes, the insecure service works fine, but we manage all our devices remotely so using that is not an option.

**Comment by nathanfaber** [comment]
I just turned it on but I did have to use a specific certificate and it works on failover.
Can you look at `/ip service print detail where name="www-ssl"` on both the active and standby? Is it using an explicit certificate? I think that may be the problem, you might need to explicitly generate one and you might need to import it to both, I do this for our OpenVPN keys into the certificate store.

**Comment by nathanfaber** [comment]
This is what I use to import certificates on reboot (sync'd automatically by the HA sync):
```
/system scheduler add name=on_reboot_fix_certifcates on-event="/certificate remove [find]\
    \n/certificate import file-name=foo.com.crt passphrase=\"\"\
    \n/certificate import file-name=foo.com.key passphrase=XXXXXX" policy=\
    ftp,reboot,read,write,policy,test,password,sniff,sensitive start-time=startup

```

**Comment by miken32** [comment]
Yes, output of `/ip service print detail where name="www-ssl"` is the same on both devices, and the cert name is specified. **However**, `/certificate print` on the standby shows no `K` flag. So this is the problem.

**Comment by nathanfaber** [comment]
Yes, I think you need to use my import script to import the keys into the keystore. In theory, I believe you can import them once but when you replace one side of the hardware, you will need to remember to do this step. That is why I simply keep it all on the filesystem and clear/import on every reboot. Some trade off to keeping the private keys/passphrases on the filesystem.

Please try the import and see if that resolves it for you.

**Comment by miken32** [comment]
I can give it a shot. Would be nice if the script did this automatically. The certificate is being imported (presumably by your script?) just not the key.

**Comment by nathanfaber** [comment]
The script can't. The public key is in the backup, the private is not. You cannot export a private key from the RouterOS keystore.

**Comment by miken32** [comment]
That makes sense. Boot script seems to be working well, thanks.
