### ISSUE TITLE
Softwareupdate on HA routers

### ISSUE THREAD

**Issue by AndreasMagdeburg** [svlsResearch/ha-mikrotik#24]
If I have installed ha-mikrotik on a pair of routers, what is the best procedure for updating the software of both routers (v6.49.2 to v6.49.3)? Of course, you should have tested the basic functionality of ha-mikrotik on the new software before the update.

**Comment by reinistihovs** [comment]
Hi!


1) backup!
2) Start update on master "HA  A" router
3) "HA B" router will automatically become master, wait for couple of minutes and run Update again, now on "HA-B"
4) "HA A" will become master again, wait for couple minutes and run firmware upgrade, reboot the router.
5) "HA B" is now master again, run firmware upgrade and reboot the router
6) Done "HA A" is master now and both devices are updated
