### ISSUE TITLE
HA interface through switch

### ISSUE THREAD

**Issue by mrgadget** [svlsResearch/ha-mikrotik#5]
We have a requirement to run the HA interface through a switch (as the routers aren't in the same datacenter).  It seems that by default all MACs are duplicated to the standby router - including the HA interface.  This means, when traffic is put through a switch, it falls over as a MAC can only exist on one port.

I found this line in ha_startup (commented):
`#/interface ethernet reset-mac-address`

We don't require the replication of MACs, so uncommenting this I thought would do the trick - but on new versions this command actually waits for input (interface number) - to get it to run on all interfaces I appended [find] ie:
`/interface ethernet reset-mac-address [find]`

I then thought as one further option that if people _do_ want MAC replication but just not on the HA interface, this line works:
`/interface ethernet reset-mac-address [find interface="$haInterface"]`

Or am I doing/understanding this wrong?

**Comment by nathanfaber** [comment]
This seems reasonable. I don't see any reason why $haInterface can't have their respective original MAC, just as you suggested. Does this satisfy your requirement or you still need a full reset of all interfaces for your setup?

It seems like the simple single $haInterface reset would work and be backwards compatible, so we could just make it the default assuming that all proves out.

**Comment by nathanfaber** [comment]
Implemented. #
